name: Ben Stuckey
favicon: null
layout_spectrum: 0.8389035416767001
typography_spectrum: 0.49052826780825853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.38378638424910605
  lightness: 0.5766339062247425
  saturation: 0.7379744539503008
  rhythmicContrast: 0.5921412771567702
purpose: []
